package MsSqlTest;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * Interaction logic for JFrame3.
 */
public class JFrame3 extends javax.swing.JFrame
{
    //<editor-fold defaultstate="collapsed" desc="Fields">
    
    // The database connectionString.
    private String url = "jdbc:sqlserver://localhost:1433;databaseName=MsSqlTestDatabase";
    
    // The username of the database account.
    String username = "root";
    
    // The password of the database account.
    String password = "RootUser0123456789";

    // The Id value.
    private int id;
    
    // The Name value.
    private String name;
    
    // </editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Constructors">
    
    /**
     * Creates new form JFrame3.
     */
    public JFrame3()
    {
        initComponents();
    }
    
    // </editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Methods">

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Type:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the ActionPerformed event of the jButton1 control.
     * @param evt The ActionEvent instance containing the event data.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // List
        GetData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Handles the ActionPerformed event of the jButton2 control.
     * @param evt The ActionEvent instance containing the event data.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add
        try
        {
            // The fields must not be empty.
            if (name != null && !name.isEmpty())
            {
                id = 0;
                boolean matchFound = false;
                boolean deletedFound = false;

                // Open a connection to the database.
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection(url, username, password);

                // Get the items from the Relationships table.
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM [MsSqlTestDatabase].[dbo].[Relationships]");
                
                // Get the number of the existing items.
                while (rs.next())
                {
                    id++;
                    
                    if (rs.getString("Name") == name && !matchFound && rs.getBoolean("IsDeleted") == false)
                    {
                        matchFound = true;
                        
                        break;
                    }
                    
                    if (rs.getString("Name") == name && !deletedFound && rs.getBoolean("IsDeleted") == true)
                    {
                        deletedFound = true;
                        
                        break;
                    }
                }

                // Close the resultSet.
                rs.close();
                
                if (!matchFound)
                {
                    if (!deletedFound)
                    {
                        // Add new item to the Relationships table.
                        PreparedStatement ps = conn.prepareStatement("INSERT INTO [MsSqlTestDatabase].[dbo].[Relationships] (Id, Name, IsDeleted) VALUES (?, ?, ?)");

                        // Set the values of the preparedStatement.
                        ps.setInt(1, id + 1);
                        ps.setString(2, name);
                        ps.setBoolean(6, false);

                        // Execute.
                        ps.execute();

                        // Close the preparedStatement.
                        ps.close();
                    }
                    else
                    {
                        // Edit the IsDeleted value to false.
                        PreparedStatement ps = conn.prepareStatement("UPDATE [MsSqlTestDatabase].[dbo].[Relationships] SET IsDeleted = ? WHERE Id = ?");

                        // Set the values of the preparedStatement.
                        ps.setBoolean(1, false);
                        ps.setInt(2, id);

                        // Update the table.
                        ps.executeUpdate();

                        // Close the preparedStatement.
                        ps.close();
                    }
                }

                // Close the connection.
                conn.close();

                // Refresh.
                GetData();
            }
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Handles the ActionPerformed event of the jButton3 control.
     * @param evt The ActionEvent instance containing the event data.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Edit
        try
        {
            // The fields must not be empty.
            if (name != null && !name.isEmpty())
            {
                // An item must be selected in the jTable.
                if (jTable1.getSelectedRow() >= 0)
                {
                    // Get the Id value of the selected item.
                    id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

                    // Open a connection to the database.
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection conn = DriverManager.getConnection(url, username, password);

                    // Edit the values.
                    PreparedStatement ps = conn.prepareStatement("UPDATE [MsSqlTestDatabase].[dbo].[Relationships] SET Name = ? WHERE Id = ?");

                    // Set the values of the preparedStatement.
                    ps.setString(1, name);
                    ps.setInt(5, id);

                    // Update the table.
                    ps.executeUpdate();

                    // Close the preparedStatement and the connection.
                    ps.close();
                    conn.close();

                    // Refresh
                    GetData();
                }
            }
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Handles the ActionPerformed event of the jButton4 control.
     * @param evt The ActionEvent instance containing the event data.
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Delete
        try
        {
            // An item must be selected in the jTable.
            if (jTable1.getSelectedRow() >= 0)
            {
                /* Logical Delete */
                // Get the Id value of the selected item.
                id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

                // Open a connection to the database.
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection(url, username, password);

                // Edit the IsDeleted value to true.
                PreparedStatement ps = conn.prepareStatement("UPDATE [MsSqlTestDatabase].[dbo].[Relationships] SET IsDeleted = ? WHERE Id = ?");

                // Set the values of the preparedStatement.
                ps.setBoolean(1, true);
                ps.setInt(2, id);

                // Update the table.
                ps.executeUpdate();

                // Close the preparedStatement and the connection.
                ps.close();
                conn.close();
                
                // Refresh
                GetData();
            }
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Handles the ActionPerformed event of the jButton5 control.
     * @param evt The ActionEvent instance containing the event data.
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Close
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Handles the KeyReleased event of the jTextField1 control.
     * @param evt The WindowEvent instance containing the event data.
     */
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        name = jTextField1.getText();
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * Handles the MouseClicked event of the jTable1 control.
     * @param evt The MouseEvent instance containing the event data.
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // An item must be selected in the jTable.
        if (jTable1.getSelectedRow() >= 0)
        {
            try
            {
                // Get the Id value of the selected item.
                int selectedRowIndex = jTable1.getSelectedRow();

                // Give the jTextField texts the selected values.
                jTextField1.setText(jTable1.getValueAt(selectedRowIndex, 2).toString());
            }
            catch (Exception e)
            {
                // Empty the jTextField texts.
                jTextField1.setText("");
            }
        }
        else
        {
            // Empty the jTextField texts.
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * Handles the WindowOpened event of the form control.
     * @param evt The WindowEvent instance containing the event data.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Preset values.
        GetData();
    }//GEN-LAST:event_formWindowOpened

    /**
     * Gets the data.
     */
    private void GetData()
    {
        try
        {
            // Clear existing items.
            DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
            dm.getDataVector().removeAllElements();
            
            // Open a connection to the database.
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection(url, username, password);
            
            // Get the items from the Relationships table.
            ArrayList<Relationship> relationships = new ArrayList<>();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM [MsSqlTestDatabase].[dbo].[Relationships] WHERE IsDeleted = 0");

            // Store the items in a Relationship list.
            while (rs.next())
            {
                Relationship relationship = new Relationship();
                
                relationship.setId(rs.getInt("Id"));
                relationship.setName(rs.getString("Name"));
                relationship.setIsDeleted(rs.getBoolean("IsDeleted"));
                
                relationships.add(relationship);
            }
            
            // Close the resultSet, the statement and the connection.
            rs.close();
            stmt.close();
            conn.close();
            
            // Fill the jTable rows with the values of the Relationships table.
            for (int i = 0; i < relationships.size(); i++)
            {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
                model.addRow(new Object[]
                {
                    relationships.get(i).getId(),
                    relationships.get(i).getName()
                });
            }
        }
        catch (Exception e)
        {
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
}
